name: PHPStan

on:
  push:
    branches: [main]
    paths:
      - "**.php"
  pull_request:
    branches: [main]
    paths:
      - "**.php"

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: none

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install composer dependencies
        uses: ramsey/composer-install@v1

      - name: Generate key
        run: php artisan key:generate

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
