name: PHP Linting

on:
  push:
    branches: [main]
    paths:
      - "**.php"
  pull_request:
    branches: [main]
    paths:
      - "**.php"

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@1.0.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true
